[package]
authors = ["The Gtk-rs Project Developers"]
description = "Rust bindings for the GLib library"
documentation = "http://gtk-rs.org/docs/glib/"
homepage = "http://gtk-rs.org/"
keywords = ["glib", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "glib"
repository = "https://github.com/gtk-rs/glib"
version = "0.1.3"

[dependencies]
bitflags = "0.5"
glib-sys = "^0.3.4"
gobject-sys = "^0.3.4"
lazy_static = "0.2"
libc = "0.2"

[features]
v2_38 = ["glib-sys/v2_38", "gobject-sys/v2_38"]
v2_40 = ["v2_38", "glib-sys/v2_40"]
v2_44 = ["v2_40", "glib-sys/v2_44", "gobject-sys/v2_44"]
v2_46 = ["v2_44", "glib-sys/v2_46", "gobject-sys/v2_46"]
v2_48 = ["v2_46", "glib-sys/v2_48"]
v2_50 = ["v2_48", "glib-sys/v2_50"]

[lib]
name = "glib"
